version: '3.7'

volumes:
  postgres_data:
  redis_data:

services:

  db:
    restart: always
    image: postgres:11
    container_name: pgfb01
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  redis:
    # image: "redis:alpine"
    container_name: rdfb01
    volumes:
      - redis_data:/data
    # ports:
    #   - "6379"

    image: "redis:alpine"

    command: redis-server

    ports:
     - "6379:6379"

    # volumes:
    # - redis-data:/var/lib/redis
    # - redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    # networks:
    #   node_net:
    #     ipv4_address: 172.28.1.4

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    container_name: webfb01
    environment:
      - ENVIRONMENT=development

    depends_on:
      - db
    volumes:
      - ./code:/code

    ports:
      - "8000:8000"