FROM python:3.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code
# create the appropriate directories


RUN apt-get update && apt-get install -y gettext libgettextpo-dev zlib1g libjpeg-dev

# RUN pip install --upgrade pip

COPY Pipfile Pipfile.lock /code/
RUN pip install pipenv && pipenv install --system

# COPY auto_server_f/requirements.txt /scripts/
# RUN pip install --no-cache-dir -r /scripts/requirements.txt

COPY . /code/