# Generated by Django 3.2.7 on 2021-10-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountfacebook',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountfacebook',
            name='token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='accountfacebook',
            name='cookie',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='accountfacebook',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountfacebook',
            name='userid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountfacebook',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
