# Generated by Django 3.2.8 on 2021-10-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211005_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('privacy', models.CharField(default='', max_length=10)),
                ('group_id', models.CharField(default='', max_length=25)),
                ('account_facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.accountfacebook')),
            ],
        ),
    ]
