# Generated by Django 3.2.8 on 2021-10-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupfacebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfacebook',
            name='account_facebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='chat.accountfacebook'),
        ),
        migrations.CreateModel(
            name='PostFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=150)),
                ('group_id', models.CharField(default='', max_length=255)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='image', verbose_name='post')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('account_facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='chat.accountfacebook')),
            ],
        ),
    ]
