# Generated by Django 3.2.8 on 2021-10-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_postfacebook_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfacebook',
            name='file',
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, default='', null=True, upload_to='image', verbose_name='post')),
                ('post_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.postfacebook')),
            ],
        ),
    ]
