# Generated by Django 3.2.8 on 2021-10-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211010_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfacebook',
            name='file',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image', verbose_name='post'),
        ),
    ]
