# Generated by Django 3.2.8 on 2021-10-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_postfacebook_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='image', verbose_name='post'),
        ),
    ]
