# Generated by Django 3.2.8 on 2021-10-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_imagepost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfacebook',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.postfacebook'),
        ),
    ]
